CREATE TABLE PhongBan
(
TenCot VARCHAR(10),
KieuDuLieu VARCHAR(10),
KichThuoc INT,
RangBuoc VARCHAR NOT NULL PRIMARY KEY,
MoTa VARCHAR(20) NULL,
);
GO

CREATE TABLE NhanVien
(
TenCot VARCHAR(10),
KieuDuLieu VARCHAR(10),
KichThuoc INT,
RangBuoc VARCHAR NOT NULL PRIMARY KEY,
MoTa VARCHAR(20) NULL,
);
GO

CREATE TABLE LuongDA
(
TenCot VARCHAR(10),
KieuDuLieu VARCHAR(10),
KichThuoc INT,
RangBuoc VARCHAR NOT NULL PRIMARY KEY,
MoTa VARCHAR(20) NULL,
);
GO
